#: include widgets/donut_chart.kv
#:import Window kivy.core.window.Window

BoxLayout:
    orientation: 'vertical'

    Label:
        text: 'Chart:'

    BoxLayout:
        orientation: 'horizontal'

        DonutChart:
            size_hint: None, None
            size: Window.width * 0.4, Window.width * 0.4
            angle: 100

        DonutChart:
            size_hint: None, None
            size: Window.width * 0.4, Window.width * 0.4
            angle: 240

    BoxLayout:
        orientation: 'horizontal'

        DonutChart:
            size_hint: None, None
            size: Window.width * 0.4, Window.width * 0.4
            angle: 10

        DonutChart:
            size_hint: None, None
            size: Window.width * 0.4, Window.width * 0.4
            angle: 300


    Label:
        text: 'text'
