#: include widgets/donut_chart.kv

BoxLayout:
    orientation: 'vertical'

    Label:
        text: 'Chart:'

    BoxLayout:
        orientation: 'horizontal'

        DonutChart:
            size_hint: None, None
            size: 200, 200
            angle: 100

        DonutChart:
            size_hint: None, None
            size: 300, 300
            angle: 240

    Label:
        text: 'text'
