<DonutChart>:
    canvas:
        # Фон
        Color:
            rgba: self.colors[0]
        Ellipse:
            pos: self.center_x - self.chart_size[0] / 2, self.center_y - self.chart_size[0] / 2
            size: self.chart_size[0], self.chart_size[0]

        # Полоса прогресса
        Color:
            rgba: self.colors[1]
        Ellipse:
            pos: self.center_x - self.chart_size[0] / 2, self.center_y - self.chart_size[0] / 2
            size: self.chart_size[0], self.chart_size[0]
            angle_start: 0
            angle_end: self.angle
            texture: root.gradient_texture if root.gradient_texture else None

        # Полоса остатка
        Color:
            rgba: self.colors[2]
        Ellipse:
            pos: self.center_x - self.chart_size[0] / 2, self.center_y - self.chart_size[0] / 2
            size: self.chart_size[0], self.chart_size[0]
            angle_start: self.angle
            angle_end: 360

        # Внутренняя зона
        Color:
            rgba: self.colors[3]
        Ellipse:
            size: self.chart_size[1], self.chart_size[1]
            pos: self.center_x - self.chart_size[1] * 0.5, self.center_y - self.chart_size[1] * 0.5

    on_size: root.set_size(self.height)
