<ListItem>
    orientation: 'horizontal'
    size_hint_y: None
    height: 60

    Label:
        text: '$: '

    Label:
        id: total_cost
        text: '0'
        value: 0

    Label:
        text: 'Д: '

    Label:
        id: parts_cost
        text: '0'
        value: 0

    Label:
        id: payment_type
        text: 'БН'

    Label:
        id: percentage
        text: '50%'
        value: 0.5

    Button:
        id: remove_button
        text: 'X'